#!/bin/sh

readonly WORKSPACE="graphql.xcworkspace"
readonly DERIVEDDATA="$(pwd)/target"

main() {
  xcodebuild -workspace $WORKSPACE -derivedDataPath $DERIVEDDATA -configuration Release -scheme 'GraphQL iOS' build | xcpretty
  xcodebuild -workspace $WORKSPACE -derivedDataPath $DERIVEDDATA -configuration Release -scheme 'GraphQL watchOS' build | xcpretty
  xcodebuild -workspace $WORKSPACE -derivedDataPath $DERIVEDDATA -configuration Release -scheme 'GraphQL tvOS' build | xcpretty
  xcodebuild -workspace $WORKSPACE -derivedDataPath $DERIVEDDATA -configuration Release -scheme 'GraphQL OS X' build | xcpretty
  xcodebuild -workspace $WORKSPACE -derivedDataPath $DERIVEDDATA -scheme 'GraphQL iOS Tests' -destination 'platform=iOS Simulator,OS=9.3,name=iPhone 6s' test | xcpretty
  xcodebuild -workspace $WORKSPACE -derivedDataPath $DERIVEDDATA -scheme 'GraphQL tvOS Tests' -destination 'platform=tvOS Simulator,OS=9.2,name=Apple TV 1080p' test | xcpretty
  xcodebuild -workspace $WORKSPACE -derivedDataPath $DERIVEDDATA -scheme 'GraphQL OS X Tests' -destination 'platform=OS X,arch=x86_64' test | xcpretty
}
main
